version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - npm ci

  build:
    commands:
      - npm run build

artifacts:
<<<<<<< HEAD
  files: '/out/**/*'
  discard-paths: yes
=======
  files: '**/*'
  base-directory: 'out'
>>>>>>> 72dbb03 (aws build and deploy : adding buildspec.yml)
