version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.10.0

  pre_build:
    commands:
      - npm i

  build:
    commands:
      - npm run build

artifacts:
  files: '/out/**/*'
  discard-paths: yes
